project:
  type: website
  output-dir: docs
  
website:
  title: "Abdelaziz A. Awad"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - publications.qmd
      - contact.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/Drzezo55/mywebsite
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2026, Abdelaziz A. Awad"

format:
  html:
    theme: Quartz 
    toc: true

editor: source

